/* Generated by GOB (v2.0.11)   (do not edit directly) */



/* Games Scores Dialog - Display high scores
 *
 * Copyright (c) 2004 by Callum McKenzie
 *
 */


#line 22 "games-scores-dialog.gob"
#line 14 "games-scores-dialog-private.h"
#ifndef __GAMES_SCORES_DIALOG_PRIVATE_H__
#define __GAMES_SCORES_DIALOG_PRIVATE_H__

#include "games-scores-dialog.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>

#line 31 "games-scores-dialog.gob"
#line 29 "games-scores-dialog-private.h"
struct _GamesScoresDialogPrivate {
#line 48 "games-scores-dialog.gob"
	GtkWidget * message;
#line 49 "games-scores-dialog.gob"
	GtkWidget * hdiv;
#line 50 "games-scores-dialog.gob"
	GtkWidget * combo;
#line 51 "games-scores-dialog.gob"
	GtkWidget * label;
#line 52 "games-scores-dialog.gob"
	GtkWidget * catbar;
#line 53 "games-scores-dialog.gob"
	GtkListStore * list;
#line 54 "games-scores-dialog.gob"
	GtkTreeView * treeview;
#line 55 "games-scores-dialog.gob"
	GtkTreeViewColumn * column;
#line 56 "games-scores-dialog.gob"
	gchar * domain;
#line 57 "games-scores-dialog.gob"
	GHashTable * categories;
#line 58 "games-scores-dialog.gob"
	GHashTable * catindices;
#line 59 "games-scores-dialog.gob"
	gint catcounter;
#line 60 "games-scores-dialog.gob"
	gint hilight;
#line 63 "games-scores-dialog.gob"
	gint style;
#line 59 "games-scores-dialog-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
