/* Generated by GOB (v2.0.11)   (do not edit directly) */



/* Games Scores Dialog - Display high scores
 *
 * Copyright (c) 2004 by Callum McKenzie
 *
 */


#include <glib.h>
#include <glib-object.h>
#ifndef __GAMES_SCORES_DIALOG_H__
#define __GAMES_SCORES_DIALOG_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



  typedef enum {
    GAMES_SCORES_STYLE_PLAIN,
    GAMES_SCORES_STYLE_TIME,
  } GamesScoresStyle;

  typedef enum {
    GAMES_SCORES_CLOSE_BUTTON = 1,
    GAMES_SCORES_NEW_GAME_BUTTON = 2,	
    GAMES_SCORES_UNDO_BUTTON = 4,
    GAMES_SCORES_QUIT_BUTTON = 8,
  } GamesScoresButtons;




#include <gtk/gtk.h>


/*
 * Type checking and casting macros
 */
#define GAMES_TYPE_SCORES_DIALOG	(games_scores_dialog_get_type())
#define GAMES_SCORES_DIALOG(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), games_scores_dialog_get_type(), GamesScoresDialog)
#define GAMES_SCORES_DIALOG_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), games_scores_dialog_get_type(), GamesScoresDialog const)
#define GAMES_SCORES_DIALOG_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), games_scores_dialog_get_type(), GamesScoresDialogClass)
#define GAMES_IS_SCORES_DIALOG(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), games_scores_dialog_get_type ())

#define GAMES_SCORES_DIALOG_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), games_scores_dialog_get_type(), GamesScoresDialogClass)

/* Private structure type */
typedef struct _GamesScoresDialogPrivate GamesScoresDialogPrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_GAMES_SCORES_DIALOG__
#define __TYPEDEF_GAMES_SCORES_DIALOG__
typedef struct _GamesScoresDialog GamesScoresDialog;
#endif
struct _GamesScoresDialog {
	GtkDialog __parent__;
	/*< private >*/
	GamesScoresDialogPrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _GamesScoresDialogClass GamesScoresDialogClass;
struct _GamesScoresDialogClass {
	GtkDialogClass __parent__;
};


/*
 * Public methods
 */
GType	games_scores_dialog_get_type	(void);
GtkWidget * 	games_scores_dialog_new	(const gchar * domain,
					const gchar * title);
void 	games_scores_dialog_add_category	(GamesScoresDialog * self,
					const gchar * key,
					const gchar * name);
void 	games_scores_dialog_set_category	(GamesScoresDialog * self,
					const gchar * key);
void 	games_scores_dialog_set_style	(GamesScoresDialog * self,
					GamesScoresStyle style);
void 	games_scores_dialog_set_category_description	(GamesScoresDialog * self,
					const gchar * description);
void 	games_scores_dialog_set_hilight	(GamesScoresDialog * self,
					guint pos);
void 	games_scores_dialog_set_message	(GamesScoresDialog * self,
					const gchar * message);
void 	games_scores_dialog_set_buttons	(GamesScoresDialog * self,
					guint buttons);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
