/* Generated by GOB (v2.0.11)   (do not edit directly) */



/* Games Scores Dialog - Display high scores
 *
 * Copyright (c) 2005 by Callum McKenzie
 *
 */


#include <glib.h>
#include <glib-object.h>
#ifndef __GAMES_SCORES_H__
#define __GAMES_SCORES_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */




  /* GamesScore and GamesScoresStyle should be kept in sync. */
  typedef union {
    guint32 plain;
    gdouble time_double; /* minutes.seconds */
  } GamesScore;

  typedef enum {
    GAMES_SCORES_STYLE_PLAIN,
    GAMES_SCORES_STYLE_TIME,
  } GamesScoresStyle;

  typedef struct {
    gchar *key;  /* A unique identifier (warning: this is used to generate the
		  * scores file name, so it should match the old domains) */
    gchar *name; /* A human-readable description. */
  } GamesScoresCategory;

  /* All elements get copied so the creator stays the owner. */
  typedef struct {
    GamesScoresCategory ** categories; /* NULL terminated! */
    gchar * deflt; /* The key of the default category. */
    gchar * filename;
    GamesScoresStyle style;
  } GamesScoresDescription;



#include <gtk/gtk.h>


/*
 * Type checking and casting macros
 */
#define GAMES_TYPE_SCORES	(games_scores_get_type())
#define GAMES_SCORES(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), games_scores_get_type(), GamesScores)
#define GAMES_SCORES_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), games_scores_get_type(), GamesScores const)
#define GAMES_SCORES_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), games_scores_get_type(), GamesScoresClass)
#define GAMES_IS_SCORES(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), games_scores_get_type ())

#define GAMES_SCORES_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), games_scores_get_type(), GamesScoresClass)

/* Private structure type */
typedef struct _GamesScoresPrivate GamesScoresPrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_GAMES_SCORES__
#define __TYPEDEF_GAMES_SCORES__
typedef struct _GamesScores GamesScores;
#endif
struct _GamesScores {
	GObject __parent__;
	/*< private >*/
	GamesScoresPrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _GamesScoresClass GamesScoresClass;
struct _GamesScoresClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	games_scores_get_type	(void);
GObject * 	games_scores_new	(GamesScoresDescription * description);
void 	games_scores_set_category	(GamesScores * self,
					gchar * category);
gboolean 	games_scores_add_score	(GamesScore * self,
					GamesScore score);
void 	games_scores_show	(GamesScores * self,
					gboolean hilight);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
