/* Generated by GOB (v2.0.11)   (do not edit directly) */



/* Games Scores Dialog - Display high scores
 *
 * Copyright (c) 2005 by Callum McKenzie
 *
 */


#line 54 "games-scores.gob"
#line 14 "games-scores-private.h"
#ifndef __GAMES_SCORES_PRIVATE_H__
#define __GAMES_SCORES_PRIVATE_H__

#include "games-scores.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>

#line 63 "games-scores.gob"
#line 29 "games-scores-private.h"
struct _GamesScoresPrivate {
#line 107 "games-scores.gob"
	GHashTable * categories;
#line 108 "games-scores.gob"
	gchar * currentcat;
#line 109 "games-scores.gob"
	gchar * defcat;
#line 110 "games-scores.gob"
	gboolean last_score_significant;
#line 111 "games-scores.gob"
	gint last_score_position;
#line 112 "games-scores.gob"
	GamesScoresStyle style;
#line 113 "games-scores.gob"
	gchar * filename;
#line 114 "games-scores.gob"
	int scoresfd;
#line 116 "games-scores.gob"
	GtkWidget * dialog;
#line 49 "games-scores-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
