/* Generated by GOB (v2.0.14)   (do not edit directly) */



/* Games Scores Dialog - Display high scores
 *
 * Copyright (c) 2004, 2005 by Callum McKenzie
 *
 */


#line 39 "games-scores-dialog.gob"
#line 14 "games-scores-dialog-private.h"
#ifndef __GAMES_SCORES_DIALOG_PRIVATE_H__
#define __GAMES_SCORES_DIALOG_PRIVATE_H__

#include "games-scores-dialog.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <glib/gi18n.h>
#include <gtk/gtk.h>

#line 48 "games-scores-dialog.gob"
#line 30 "games-scores-dialog-private.h"
struct _GamesScoresDialogPrivate {
#line 66 "games-scores-dialog.gob"
	GtkWidget * message;
#line 67 "games-scores-dialog.gob"
	GtkWidget * hdiv;
#line 68 "games-scores-dialog.gob"
	GtkWidget * combo;
#line 69 "games-scores-dialog.gob"
	GtkWidget * label;
#line 70 "games-scores-dialog.gob"
	GtkWidget * catbar;
#line 71 "games-scores-dialog.gob"
	GtkListStore * list;
#line 72 "games-scores-dialog.gob"
	GtkTreeView * treeview;
#line 73 "games-scores-dialog.gob"
	GtkCellRenderer * namerenderer;
#line 74 "games-scores-dialog.gob"
	GtkTreeViewColumn * column;
#line 75 "games-scores-dialog.gob"
	GtkTreeViewColumn * namecolumn;
#line 76 "games-scores-dialog.gob"
	GamesScores * scores;
#line 77 "games-scores-dialog.gob"
	GHashTable * categories;
#line 78 "games-scores-dialog.gob"
	GHashTable * catindices;
#line 79 "games-scores-dialog.gob"
	gint catcounter;
#line 80 "games-scores-dialog.gob"
	gint hilight;
#line 81 "games-scores-dialog.gob"
	gint sethilight;
#line 82 "games-scores-dialog.gob"
	gboolean preservehilight;
#line 83 "games-scores-dialog.gob"
	gulong cursor_handler_id;
#line 86 "games-scores-dialog.gob"
	gint style;
#line 70 "games-scores-dialog-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
