#!/usr/bin/env perl

#  Aisleriot Game Name Internationalizator
#
#  Copyright (C) 2001 Free Software Foundation.
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This script is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this library; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Author(s): Kenneth Christiansen <kenneth@gnu.org>

sub print_data # (array of i18n names)
{
  my (@i18n_names) = @_;

  foreach $i18n_name (@i18n_names)
  {
    print OUTFILE "gchar *s = N_(\"$i18n_name\")\n";
  }
}

sub print_header # void
{
  print OUTFILE 
  "/*\n".
  " * Translatable strings file generated by get_titles.pl.\n".
  " * Add this file to your project's POTFILES.in.\n".
  " * DO NOT compile it as part of your application.\n".
  " */\n\n";
}

sub get_raw_names
{
  my $raw_names = `ls *scm`;
  my @raw_names = split(/\n/, $raw_names);

  return @raw_names;
}

sub get_i18n_name_strings # (array of raw names) -> (array of i18n names)
{
  my (@raw_names) = @_;
  my @i18n_names;  

  foreach $raw_name (@raw_names)
  {
    chomp;
    $raw_name =~ s/^(.)(.*).scm$/\U$1\E$2/;
    $raw_name =~ s/_/ /g; 

    push @i18n_names, $raw_name;
  }

  return @i18n_names;
}

# -- Main -- #

open OUTFILE, ">translatable_game_names.h";
my @raw_names = &get_raw_names;
my @i18n_names = &get_i18n_name_strings (@raw_names);
foreach $hej (@i18n_names) {
  print "$hej\n";
}
&print_header;
&print_data (@i18n_names);
