/* XPM */
static char * tb_new_seed_xpm[] = {
"24 24 104 2",
"  	c None",
". 	c #000000",
"+ 	c #ADAD9C",
"@ 	c #959585",
"# 	c #DCDCC5",
"$ 	c #DFDFC8",
"% 	c #242424",
"& 	c #A7A796",
"* 	c #D7D7C1",
"= 	c #D9D9C3",
"- 	c #DCDCC4",
"; 	c #DDDDC7",
"> 	c #E1E1CA",
", 	c #A6A694",
"' 	c #D6D6BF",
") 	c #D8D8C2",
"! 	c #DBDBC4",
"~ 	c #DFDFC7",
"{ 	c #E3E3CB",
"] 	c #B2B29F",
"^ 	c #7C7C7C",
"/ 	c #646464",
"( 	c #D5D5BD",
"_ 	c #D5D5BF",
": 	c #D7D7C0",
"< 	c #DADAC3",
"[ 	c #636358",
"} 	c #AFAF9C",
"| 	c #CBCBB6",
"1 	c #4D4D45",
"2 	c #343434",
"3 	c #E7E7E7",
"4 	c #373736",
"5 	c #B8B8A6",
"6 	c #D3D3BC",
"7 	c #D9D9C2",
"8 	c #ACAC99",
"9 	c #E5E5CD",
"0 	c #33332E",
"a 	c #34342F",
"b 	c #EEEED5",
"c 	c #ECECEC",
"d 	c #EDEDED",
"e 	c #3D3D37",
"f 	c #CECEB7",
"g 	c #4A4A42",
"h 	c #4C4C44",
"i 	c #9A9A8A",
"j 	c #9E9E8E",
"k 	c #F1F1D8",
"l 	c #A5A594",
"m 	c #EEEEE5",
"n 	c #3C3C3C",
"o 	c #8F8F80",
"p 	c #45453D",
"q 	c #F2F2D9",
"r 	c #F3F3DA",
"s 	c #EEEEE6",
"t 	c #505050",
"u 	c #929282",
"v 	c #D1D1B9",
"w 	c #ABAB98",
"x 	c #4B4B43",
"y 	c #1A1A17",
"z 	c #9C9C8C",
"A 	c #353530",
"B 	c #A2A291",
"C 	c #F4F4DB",
"D 	c #F5F5DC",
"E 	c #969686",
"F 	c #D2D2BC",
"G 	c #AAAA98",
"H 	c #959586",
"I 	c #32322D",
"J 	c #69695E",
"K 	c #BEBEAB",
"L 	c #797973",
"M 	c #D8D8C1",
"N 	c #494942",
"O 	c #98988F",
"P 	c #AEAE9C",
"Q 	c #191917",
"R 	c #828274",
"S 	c #868678",
"T 	c #818174",
"U 	c #E0E0C8",
"V 	c #B0B09D",
"W 	c #9B9B8B",
"X 	c #35352F",
"Y 	c #BEBEAE",
"Z 	c #B5B5A2",
"` 	c #EAEAD2",
" .	c #B8B8A5",
"..	c #4E4E4E",
"+.	c #E8E8D0",
"@.	c #E9E9D1",
"#.	c #EDEDD4",
"$.	c #EFEFD6",
"%.	c #EBEBD3",
"&.	c #ECECD4",
"*.	c #F0F0D7",
"=.	c #BBBBA8",
"-.	c #CDCDB8",
";.	c #A6A696",
"                                                ",
"                                                ",
"                          .                     ",
"                      . . + .                   ",
"                  . . @ # $ %                   ",
"              . . & * = - ; > .                 ",
"          . . , ' * * ) ! ~ { ] .               ",
"        . ^ / ' ( _ : < [ } | 1 2               ",
"        . 3 4 5 6 * 7 8 . 9 0 a b .             ",
"        . c d e f _ ! g h i . j k l .           ",
"        . m m n o p . . . . . . q r .           ",
"        . s t u v w x y z . A B r C D .         ",
"        . . E F G H I 1 J . B C C D D K .       ",
"        . L M 7 N . . . . . . D D D D D ) .     ",
"        . O ! # P Q 0 R . S B D D D D D T .     ",
"          . ~ U V . W J X q C D D D D . .       ",
"          . Y 9 | Z `  ._ r C D D < .           ",
"            ..+.@.` #.$.q r C q R .             ",
"            . %.&.#.$.k q q < .                 ",
"              . $.*.k q @.l .                   ",
"              . =.q r -.1 .                     ",
"                . r ;..                         ",
"                  . .                           ",
"                                                "};

/* XPM */
static char * tb_score_xpm[] = {
"24 24 4 1",
" 	c None",
".	c #000000",
"+	c #FF0000",
"@	c #0000FF",
"                        ",
"                        ",
"  .                     ",
"  .                     ",
"  .                     ",
"  .  .......            ",
"  .  .+++++.            ",
"  .  .+++++.            ",
"  .  .+++++.            ",
"  .  .+++++.  .......   ",
"  .  .+++++.  .@@@@@.   ",
"  .  .+++++.  .@@@@@.   ",
"  .  .+++++.  .@@@@@.   ",
"  .  .+++++.  .@@@@@.   ",
"  .  .+++++.  .@@@@@.   ",
"  .  .+++++.  .@@@@@.   ",
"  .  .+++++.  .@@@@@.   ",
"  ....................  ",
"  ....................  ",
"  ....................  ",
"                        ",
"                        ",
"                        ",
"                        "};
